site_name: Ariadne Documentation
use_directory_urls: false
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - mkdocs-autoapi:
      autoapi_dir: src
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Notebooks:
      - Exact mapping: notebooks/01_evaluate_exact_mapping.ipynb

extra_css:
  - stylesheets/extra.css